ZoneParserI Class Reference
Public Member Functions
java.util.Enumeration
*
< ZPZoneEntry > zoneElements ()
int zoneSize ()
java.util.Vector items (String name)
java.util.Enumeration
*
< ZPAliasEntry > aliasElements ()
ZPAliasEntry[] aliasArray ()
int aliasSize ()
abstract void setReader (java.io.Reader is)
abstract void setDebug (boolean debug)
ZoneParserI (java.io.InputStream in)
Create a parser with a new stream, defaulting to no debug, and verbose ZP debug.
ZoneParserI ()
Create a parser with a no stream or reader, fairly uncivilized, defaulting to no debug.
ZoneParserI (java.io.InputStream in, boolean debugMe)
Create a parser with a new stream.
ZoneParserI (Reader in)
Create a parser with a new reader, defaulting to no debug, and verbose ZP debug.
ZoneParserI (Reader in, boolean debugMe)
Create a parser, setting the debug to true or false.
ZoneParserI (java.util.Properties properties)
Create a parser, setting the debug to true or false.
void testSummary (String args[])
To test/show a descendant class, with a created parser, feed in the stdin, parse what it can, and summarize the results to stdout.
Detailed Description
JVM Options
JVM Options debug.verboseTokenizer (values: true, Alias4Parser, AliShowZoneParser, BNAZoneParser, DeviceAliasParser, NicknameParser, ShowZoneParser, VW4InvalidAddedParser) can be set to either `true`, or to the name of a specific parser (ie ShowZoneParser) to cause the parser's tokenizing and returned tokens to be displayed. Of note: this will show when the parser sees a value it doesn't like, such as an improper symbol, word, or key term. This can be helpful in diagnosing why the parser gave up and/or the calling process didn't feel this parser's results were worth keeping or using. Alias4Parser and NicknameParser are not LALR-based but do give some indications by this option.
JVM Options
JVM Options
java -Ddebug.verboseTokenizer=NicknameParser -jar fcparser.jar -N ...
JVM Options
JVM Options debug.dumpAliases (values: true, Alias4Parser, AliShowZoneParser, BNAZoneParser, DeviceAliasParser, NicknameParser, ShowZoneParser, VW4InvalidAddedParser) can be used to tell most parsers to dump out their results for diagnostics. Setting it to `true` would cause all to dump their results; setting to the name of a Parser (ie ShowZoneParser, VW4InvalidAddedParser, NicknameParser) would cause that individual parser to show its results. These names are the same names listed at the end of a parse attempt for convenience/aide-memoire.
JVM Options
JVM Options
java -Ddebug.dumpAliases=AliShowZoneParser -jar fcparser.jar -N ...
JVM Options
JVM Options debug.dumpItems (values: Aliases, reservedAliases) can be used to tell most parsers to dump out additional results directly for diagnostics. For example, VW4InvalidAddedParser can track post-remove aliases in the mapping `reservedAliases`
JVM Options
JVM Options
java -Ddebug.dumpItems=reservedAliases -jar fcparser.jar -N ...
JVM Options
JVM Options debug.verboseAddAlias: (values: true, Alias4Parser, AliShowZoneParser, BNAZoneParser, DeviceAliasParser, ShowZoneParser, VW4InvalidAddedParser) Although not much use without looking inside the code, setting this value allows you to see when the parser is storing a new alias block/set internally for retrieval by the calling function. It might help you to see where the incorrect data is coming from.
JVM Options
JVM Options debug.verboseAddZone: (values: true, Alias4Parser, AliShowZoneParser, BNAZoneParser, DeviceAliasParser, ShowZoneParser, VW4InvalidAddedParser) Although not much use without looking inside the code, setting this value allows you to see when the parser is storing a new zone block internally for retrieval by the calling function. It might help you to see where the incorrect data is coming from.
JVM Options
JVM Options debug.verboseAppendZone: (values: true, Alias4Parser, AliShowZoneParser, BNAZoneParser, DeviceAliasParser, ShowZoneParser, VW4InvalidAddedParser) Although not much use without looking inside the code, setting this value allows you to see when the parser is adding data to an existing zone value internally for retrieval by the calling function. It might help you to see where the incorrect data is coming from.
JVM Options
JVM Options debug.yystate: (values: true, AliShowZoneParser, BNAZoneParser, DeviceAliasParser, ShowZoneParser, VW4InvalidAddedParser) Although not much use without looking inside the code, setting this value allows you to see the debug information from inside the LALR state machine itself. This might give some insight as to why some parse attempts are failing, or how the state-machine needs to be extended to accommodate more situations.
Definition at line 72 of file ZoneParserI.java.
Constructor & Destructor Documentation
ZoneParserI (java.io.InputStream in) [inline]
Create a parser with a new stream, defaulting to no debug, and verbose ZP debug.
Parameters
in InputStream that is the source of bytes to consume
Definition at line 115 of file ZoneParserI.java.
ZoneParserI () [inline]
Create a parser with a no stream or reader, fairly uncivilized, defaulting to no debug.
Definition at line 124 of file ZoneParserI.java.
ZoneParserI (java.io.InputStream in, boolean debugMe) [inline]
Create a parser with a new stream.
Parameters
in InputStream that is the source of bytes to consume
debugMe true for debugging, false for no debug.
Definition at line 136 of file ZoneParserI.java.
ZoneParserI (Reader in) [inline]
Create a parser with a new reader, defaulting to no debug, and verbose ZP debug.
Parameters
in Reader that is the source of bytes to consume
Definition at line 147 of file ZoneParserI.java.
ZoneParserI (Reader in, boolean debugMe) [inline]
Create a parser, setting the debug to true or false.
Parameters
in Reader that is the source of bytes to consume
debugMe true for debugging, false for no debug.
Definition at line 159 of file ZoneParserI.java.
References ZoneParserI.setDebug(), and ZoneParserI.setReader().
ZoneParserI (java.util.Properties properties) [inline]
Create a parser, setting the debug to true or false.
Parameters
properties additional name-value pair collection
Definition at line 172 of file ZoneParserI.java.
Member Function Documentation
ZPAliasEntry [] aliasArray () [inline]
Definition at line 95 of file ZoneParserI.java.
Referenced by ZoneParserI.testSummary().
java.util.Enumeration<ZPAliasEntry> aliasElements () [inline]
Definition at line 90 of file ZoneParserI.java.
int aliasSize () [inline]
Definition at line 100 of file ZoneParserI.java.
Referenced by ZoneParserI.testSummary().
java.util.Vector items (String name) [inline]
Definition at line 88 of file ZoneParserI.java.
Referenced by ZoneParserI.testSummary().
abstract void setDebug (boolean debug) [abstract]
Referenced by ZoneParserI.ZoneParserI().
abstract void setReader (java.io.Reader is) [abstract]
Referenced by ZoneParserI.ZoneParserI().
void testSummary (String args[]) [inline]
To test/show a descendant class, with a created parser, feed in the stdin, parse what it can, and summarize the results to stdout.
Parameters
args argc/argv from a void main() run to feed any getopt herein (currently ignored)
Definition at line 307 of file ZoneParserI.java.
References ZoneParserI.aliasArray(), ZoneParserI.aliasSize(), ZoneParserI.items(), and ZoneParserI.zoneSize().
Referenced by Alias4Parser.main(), BNAZoneParser.main(), DeviceAliasParser.main(), ShowZoneParser.main(), ShowZone2Parser.main(), AliShowZoneParser.main(), and VW4InvalidAddedParser.main().
java.util.Enumeration<ZPZoneEntry> zoneElements () [inline]
Definition at line 78 of file ZoneParserI.java.
int zoneSize () [inline]
Definition at line 83 of file ZoneParserI.java.
Referenced by ZoneParserI.testSummary().
The documentation for this class was generated from the following file:
java/ZoneParserI.java