ParserTee Class Reference
Public Member Functions
ParserTee (InputStream input, ZoneParser zp) throws java.io.IOException
Create a link in a chain of parser tees.
Static Public Member Functions
static OutputStream pipeOutputStreamTo (ZoneParser zp) throws java.io.IOException
Tee off the datastream and set it to sink into the given ZoneParser.
Detailed Description
Definition at line 11 of file ParserTee.java.
Constructor & Destructor Documentation
ParserTee (InputStream input, ZoneParser zp) throws java.io.IOException [inline]
Create a link in a chain of parser tees.
Parameters
input the incoming datastream to read from and pass through
zp a ZoneParser to consume a copy of the incoming datastream
Exceptions
java.io.IOException if PipedOutputStream(PipedInputStream) throws the same
Definition at line 58 of file ParserTee.java.
References ParserTee.pipeOutputStreamTo().
Member Function Documentation
static OutputStream pipeOutputStreamTo (ZoneParser zp) throws java.io.IOException [inline], [static]
Tee off the datastream and set it to sink into the given ZoneParser.
Returns
new OutputStream connected to the ZoneParser's input to which the tee or fork of the incoming datastream can/should be dumped
Parameters
zp a ZoneParser to consume a copy of the incoming datastream
Exceptions
java.io.IOException if PipedOutputStream(PipedInputStream) throws the same
Definition at line 42 of file ParserTee.java.
Referenced by Select2Sample.main(), and ParserTee.ParserTee().
The documentation for this class was generated from the following file:
java/ParserTee.java