SSHURLConnection Class Reference
Public Member Functions
SSHURLConnection (java.net.URL url)
void setRequestHeader (String name, String value)
Stubbed, because there's no change we want to accept yet.
void setContentType (String ignored)
Stubbed, because there's no change we want to accept yet.
java.io.OutputStream getOutputStream ()
Stubbed, because there's nothing to send us.
void connect ()
void exec (String s) throws SSHException, IOException
void disconnect ()
String server ()
String command ()
Protected Member Functions
SSHURLConnection openConnection (java.net.URL url)
openConnection(java.net.URL) overrides java.net.URLStreamHandler.openConnection(URL) by wrapping a pgsql client.
void _connect () throws IOException, SocketException, UserAuthException
Session _session () throws ConnectionException, IOException, TransportException
Protected Attributes
SSHClient client
Detailed Description
Definition at line 33 of file SSHURLConnection.java.
Constructor & Destructor Documentation
SSHURLConnection (java.net.URL url) [inline]
Definition at line 37 of file SSHURLConnection.java.
Member Function Documentation
void _connect () throws IOException, SocketException, UserAuthException [inline], [protected]
Exceptions
SocketException from client.connect()
UserAuthException from client.authPassword(...)
IOException from client.connect()
Definition at line 104 of file SSHURLConnection.java.
Referenced by SSHURLConnection._session(), and SSHURLConnection.connect().
Session _session () throws ConnectionException, IOException, TransportException [inline], [protected]
Exceptions
IOException from client.connect() in _connect()
Definition at line 128 of file SSHURLConnection.java.
References SSHURLConnection._connect().
Referenced by SSHURLConnection.exec().
String command () [inline]
Definition at line 154 of file SSHURLConnection.java.
void connect () [inline]
Definition at line 90 of file SSHURLConnection.java.
References SSHURLConnection._connect().
void disconnect () [inline]
Definition at line 141 of file SSHURLConnection.java.
void exec (String s) throws SSHException, IOException [inline]
Definition at line 136 of file SSHURLConnection.java.
References SSHURLConnection._session().
java.io.OutputStream getOutputStream () [inline]
Stubbed, because there's nothing to send us.
Definition at line 73 of file SSHURLConnection.java.
SSHURLConnection openConnection (java.net.URL url) [inline], [protected]
openConnection(java.net.URL) overrides java.net.URLStreamHandler.openConnection(URL) by wrapping a pgsql client.
Returns
populated connection as org.smallfoot.dcnmsql.SSHURLConnection(Connection)
Parameters
url URL to connect to
Definition at line 85 of file SSHURLConnection.java.
String server () [inline]
Definition at line 152 of file SSHURLConnection.java.
void setContentType (String ignored) [inline]
Stubbed, because there's no change we want to accept yet.
Parameters
ignored ignored
Definition at line 68 of file SSHURLConnection.java.
void setRequestHeader (String name, String value) [inline]
Stubbed, because there's no change we want to accept yet.
Parameters
name ignored
value ignored
Definition at line 61 of file SSHURLConnection.java.
Field Documentation
SSHClient client [protected]
Definition at line 35 of file SSHURLConnection.java.
The documentation for this class was generated from the following file:
java/SSHURLConnection.java