ZoneParser Class Reference
Public Member Functions
abstract java.util.Enumeration
*
< ZPZoneEntry > zoneElements ()
abstract int zoneSize ()
abstract java.util.Vector items (String name)
abstract java.util.Enumeration
*
< ZPAliasEntry > aliasElements ()
abstract ZPAliasEntry[] aliasArray ()
abstract int aliasSize ()
abstract void setReader (java.io.Reader is)
abstract void setDebug (boolean debug)
ZoneParser (java.io.InputStream in)
Create a parser with a new stream, defaulting to no debug, and verbose ZP debug.
ZoneParser ()
Create a parser with a no stream or reader, fairly uncivilized, defaulting to no debug.
ZoneParser (java.io.InputStream in, boolean debugMe)
Create a parser with a new stream.
ZoneParser (Reader in)
Create a parser with a new reader, defaulting to no debug, and verbose ZP debug.
ZoneParser (Reader in, boolean debugMe)
Create a parser, setting the debug to true or false.
ZoneParser (java.util.Properties properties)
Create a parser, setting the debug to true or false.
void testSummary (String args[])
To test/show a descendant class, with a created parser, feed in the stdin, parse what it can, and summarize the results to stdout.
void summarize ()
Summarize the parsing results to stdout.
Detailed Description
Definition at line 5 of file ZoneParser.java.
Constructor & Destructor Documentation
ZoneParser (java.io.InputStream in) [inline]
Create a parser with a new stream, defaulting to no debug, and verbose ZP debug.
Parameters
in InputStream that is the source of bytes to consume
Definition at line 41 of file ZoneParser.java.
ZoneParser () [inline]
Create a parser with a no stream or reader, fairly uncivilized, defaulting to no debug.
Definition at line 50 of file ZoneParser.java.
ZoneParser (java.io.InputStream in, boolean debugMe) [inline]
Create a parser with a new stream.
Parameters
in InputStream that is the source of bytes to consume
debugMe true for debugging, false for no debug.
Definition at line 62 of file ZoneParser.java.
ZoneParser (Reader in) [inline]
Create a parser with a new reader, defaulting to no debug, and verbose ZP debug.
Parameters
in Reader that is the source of bytes to consume
Definition at line 73 of file ZoneParser.java.
ZoneParser (Reader in, boolean debugMe) [inline]
Create a parser, setting the debug to true or false.
Parameters
in Reader that is the source of bytes to consume
debugMe true for debugging, false for no debug.
Definition at line 85 of file ZoneParser.java.
References ZoneParser.setDebug(), and ZoneParser.setReader().
ZoneParser (java.util.Properties properties) [inline]
Create a parser, setting the debug to true or false.
Parameters
properties additional name-value pair collection
Definition at line 98 of file ZoneParser.java.
References ZoneParser.setDebug().
Member Function Documentation
abstract ZPAliasEntry [] aliasArray () [abstract]
Referenced by ZoneParser.summarize().
abstract java.util.Enumeration<ZPAliasEntry> aliasElements () [abstract]
abstract int aliasSize () [abstract]
Referenced by FCParser.loadFile(), and ZoneParser.summarize().
abstract java.util.Vector items (String name) [abstract]
abstract void setDebug (boolean debug) [abstract]
Referenced by ZoneParser.ZoneParser().
abstract void setReader (java.io.Reader is) [abstract]
Referenced by ZoneParser.ZoneParser().
void summarize () [inline]
Summarize the parsing results to stdout.
Definition at line 123 of file ZoneParser.java.
References ZoneParser.aliasArray(), ZoneParser.aliasSize(), and ZoneParser.zoneSize().
Referenced by Select2Sample.main(), FCParser.main(), and ZoneParser.testSummary().
void testSummary (String args[]) [inline]
To test/show a descendant class, with a created parser, feed in the stdin, parse what it can, and summarize the results to stdout.
Parameters
args argc/argv from a void main() run to feed any getopt herein (currently ignored)
Definition at line 112 of file ZoneParser.java.
References ZoneParser.summarize().
abstract java.util.Enumeration<ZPZoneEntry> zoneElements () [abstract]
abstract int zoneSize () [abstract]
Referenced by FCParser.loadFile(), and ZoneParser.summarize().
The documentation for this class was generated from the following file:
java/ZoneParser.java