VCenterURLConnection.VCCException Class Reference
Public Member Functions
String suggestion ()
VCCException (Throwable t, String suggestion)
VCCException (String s, String suggestion)
Protected Attributes
String suggestion = null
Detailed Description
Definition at line 25 of file VCenterURLConnection.java.
Constructor & Destructor Documentation
VCCException (Throwable t, String suggestion) [inline]
Definition at line 33 of file VCenterURLConnection.java.
References VCenterURLConnection.VCCException.suggestion().
VCCException (String s, String suggestion) [inline]
Definition at line 38 of file VCenterURLConnection.java.
References VCenterURLConnection.VCCException.suggestion().
Member Function Documentation
String suggestion () [inline]
Definition at line 28 of file VCenterURLConnection.java.
Referenced by VCenterURLConnection.VCCException.VCCException().
Field Documentation
String suggestion = null [protected]
Definition at line 27 of file VCenterURLConnection.java.
The documentation for this class was generated from the following file:
java/VCenterURLConnection.java