DeviceAliasParser Class Reference
Public Member Functions
void parse ()
void setReader (Reader in)
void run ()
void setDebug (boolean debug)
DeviceAliasParser (InputStream in, boolean debugMe)
DeviceAliasParser (java.util.Properties in)
Static Public Member Functions
static void main (String args[])
Static Public Attributes
static final short DEVICEALIAS =257
static final short NAME =258
static final short PWWN =259
static final short ALPHANUM =260
static final short PRE_SHOW =261
static final short PRE_DATABASE =262
static final short YYERRCODE =256
Detailed Description
Definition at line 86 of file DeviceAliasParser.java.
Constructor & Destructor Documentation
DeviceAliasParser (InputStream in, boolean debugMe) [inline]
Definition at line 506 of file DeviceAliasParser.java.
Referenced by DeviceAliasParser.main().
DeviceAliasParser (java.util.Properties in) [inline]
Definition at line 507 of file DeviceAliasParser.java.
Member Function Documentation
static void main (String args[]) [inline], [static]
Definition at line 510 of file DeviceAliasParser.java.
References DeviceAliasParser.DeviceAliasParser(), and ZoneParserI.testSummary().
void parse () [inline]
Definition at line 446 of file DeviceAliasParser.java.
void run () [inline]
Definition at line 493 of file DeviceAliasParser.java.
void setDebug (boolean debug) [inline]
Definition at line 504 of file DeviceAliasParser.java.
void setReader (Reader in) [inline]
Definition at line 458 of file DeviceAliasParser.java.
Field Documentation
final short ALPHANUM =260 [static]
Definition at line 214 of file DeviceAliasParser.java.
final short DEVICEALIAS =257 [static]
Definition at line 211 of file DeviceAliasParser.java.
final short NAME =258 [static]
Definition at line 212 of file DeviceAliasParser.java.
final short PRE_DATABASE =262 [static]
Definition at line 216 of file DeviceAliasParser.java.
final short PRE_SHOW =261 [static]
Definition at line 215 of file DeviceAliasParser.java.
final short PWWN =259 [static]
Definition at line 213 of file DeviceAliasParser.java.
final short YYERRCODE =256 [static]
Definition at line 217 of file DeviceAliasParser.java.
The documentation for this class was generated from the following file:
java/DeviceAliasParser.java