CIMXMLCQLURLConnection Class Reference
Data Structures
class ResultCSVPipe
PipedOutputStream to push out resultsets as CSV Nicknames.
Public Member Functions
CIMXMLCQLURLConnection (String connectionInfo, String username, String password, String path, String className, String propWWPN, String propName)
CIMXMLCQLURLConnection (java.net.URL url)
CIMXMLCQLURLConnection (java.net.URL url, String path, String className, String propWWPN, String propName)
void setRequestHeader (String name, String value)
Stubbed, because there's no change we want to accept yet.
void setContentType (String ignored)
Stubbed, because there's no change we want to accept yet.
java.io.OutputStream getOutputStream ()
Stubbed, because there's nothing to send us.
java.io.InputStream getInputStream ()
connect the result of a `SELECT hp.wwn, h.name FROM host_port hp JOIN host h ON (h.id = hp.hostid)` to something that looks readable like an InputStream
void connect ()
Static Public Member Functions
static Subject getSubjectAuth (String authInfo)
static WBEMClient getWBEMClient (java.net.URL u, String proto) throws WBEMException
Protected Member Functions
CIMXMLCQLURLConnection openConnection (java.net.URL url)
openConnection(java.net.URL) overrides java.net.URLStreamHandler.openConnection(URL) by wrapping a pgsql client.
Protected Attributes
WBEMClient client = null
WBEMClient sclient = null
CIMObjectPath cop = null
String path = `/cimv2`
String className = `CIM_Object`
String propWWPN = null
String propName = null
Detailed Description
Definition at line 49 of file CIMXMLCQLURLConnection.java.
Constructor & Destructor Documentation
CIMXMLCQLURLConnection (String connectionInfo, String username, String password, String path, String className, String propWWPN, String propName) [inline]
Definition at line 112 of file CIMXMLCQLURLConnection.java.
References CIMXMLCQLURLConnection.className, CIMXMLCQLURLConnection.path, CIMXMLCQLURLConnection.propName, and CIMXMLCQLURLConnection.propWWPN.
CIMXMLCQLURLConnection (java.net.URL url) [inline]
Definition at line 126 of file CIMXMLCQLURLConnection.java.
CIMXMLCQLURLConnection (java.net.URL url, String path, String className, String propWWPN, String propName) [inline]
Definition at line 133 of file CIMXMLCQLURLConnection.java.
References CIMXMLCQLURLConnection.className, CIMXMLCQLURLConnection.path, CIMXMLCQLURLConnection.propName, and CIMXMLCQLURLConnection.propWWPN.
Member Function Documentation
void connect () [inline]
Definition at line 347 of file CIMXMLCQLURLConnection.java.
References CIMXMLCQLURLConnection.getWBEMClient().
Referenced by CIMXMLCQLURLConnection.getInputStream().
java.io.InputStream getInputStream () [inline]
connect the result of a `SELECT hp.wwn, h.name FROM host_port hp JOIN host h ON (h.id = hp.hostid)` to something that looks readable like an InputStream
Definition at line 198 of file CIMXMLCQLURLConnection.java.
References CIMXMLCQLURLConnection.connect().
java.io.OutputStream getOutputStream () [inline]
Stubbed, because there's nothing to send us.
Oh how did I get caught in the `Royal 'We'` ?
Definition at line 189 of file CIMXMLCQLURLConnection.java.
static Subject getSubjectAuth (String authInfo) [inline], [static]
Definition at line 248 of file CIMXMLCQLURLConnection.java.
Referenced by CIMXMLCQLURLConnection.getWBEMClient().
static WBEMClient getWBEMClient (java.net.URL u, String proto) throws WBEMException [inline], [static]
Definition at line 277 of file CIMXMLCQLURLConnection.java.
References CIMXMLCQLURLConnection.getSubjectAuth().
Referenced by CIMXMLCQLURLConnection.connect().
CIMXMLCQLURLConnection openConnection (java.net.URL url) [inline], [protected]
openConnection(java.net.URL) overrides java.net.URLStreamHandler.openConnection(URL) by wrapping a pgsql client.
Returns
populated connection as org.smallfoot.cimwql.CIMXMLCQLURLConnection(Connection)
Parameters
url URL to connect to
Definition at line 306 of file CIMXMLCQLURLConnection.java.
void setContentType (String ignored) [inline]
Stubbed, because there's no change we want to accept yet.
Parameters
ignored ignored
Definition at line 184 of file CIMXMLCQLURLConnection.java.
void setRequestHeader (String name, String value) [inline]
Stubbed, because there's no change we want to accept yet.
Parameters
name ignored
value ignored
Definition at line 177 of file CIMXMLCQLURLConnection.java.
Field Documentation
String className = `CIM_Object` [protected]
Definition at line 108 of file CIMXMLCQLURLConnection.java.
Referenced by CIMXMLCQLURLConnection.CIMXMLCQLURLConnection().
WBEMClient client = null [protected]
Definition at line 104 of file CIMXMLCQLURLConnection.java.
CIMObjectPath cop = null [protected]
Definition at line 106 of file CIMXMLCQLURLConnection.java.
String path = `/cimv2` [protected]
Definition at line 107 of file CIMXMLCQLURLConnection.java.
Referenced by CIMXMLCQLURLConnection.CIMXMLCQLURLConnection().
String propName = null [protected]
Definition at line 110 of file CIMXMLCQLURLConnection.java.
Referenced by CIMXMLCQLURLConnection.CIMXMLCQLURLConnection(), and CIMXMLCQLURLConnection.ResultCSVPipe.run().
String propWWPN = null [protected]
Definition at line 109 of file CIMXMLCQLURLConnection.java.
Referenced by CIMXMLCQLURLConnection.CIMXMLCQLURLConnection(), and CIMXMLCQLURLConnection.ResultCSVPipe.run().
WBEMClient sclient = null [protected]
Definition at line 105 of file CIMXMLCQLURLConnection.java.
The documentation for this class was generated from the following file:
java/CIMXMLCQLURLConnection.java