SSHCLI Class Reference
Public Member Functions
void exec (String s, boolean dryrun)
SSHCLI ()
Static Public Member Functions
static void registerProtocols ()
Collect in a single place the process to register protocol handlers.
static void main (String args[])
Main function, as you can tell.
Detailed Description
Definition at line 18 of file SSHCLI.java.
Constructor & Destructor Documentation
SSHCLI () [inline]
Definition at line 162 of file SSHCLI.java.
References SSHCLI.registerProtocols().
Referenced by SSHCLI.main().
Member Function Documentation
void exec (String s, boolean dryrun) [inline]
Definition at line 52 of file SSHCLI.java.
static void main (String args[]) [inline], [static]
Main function, as you can tell.
this function merely parses the command-line to dispatch actions to the meat of the meal above. I'm using an actual GetOpt because, yes, I'm a UNIX/C hack, re-using 3-decades-old knowledge, but this also preserves both extensibility and the ability to use longopts in scripts as a way to self-document what the tool's doing.
No real intelligence herein except the parse-and-redirect action.
Parameters
args as you'd expect, these are commandline arguments given when the jar is activated
Always always ALWAYS provide a quick reference and a version output
Commandline Options
Commandline Options -H|--help Show a simple help screen as a reminder of options which are understood by the application
Commandline Options
Commandline Options
java -jar fcparsers.jar --help
Commandline Options
Commandline Options -V|--version Show the current release version for reference
Commandline Options
Commandline Options
java -jar fcparsers.jar --version
.3-198
Commandline Options
Commandline Options -!|--check Run an internal check that dependent drivers are available and registered
Definition at line 195 of file SSHCLI.java.
References SSHCLI.SSHCLI().
static void registerProtocols () [inline], [static]
Collect in a single place the process to register protocol handlers.
This function checks for current protocol handlers and adds the ones we bring to that list. If no `java.protocol.handler.pkgs` exists, we simply provide one. System Properties are overwritten in this process.
as the number of handlers increases, we can make corresponding changes herein without consuming projects having to know or care about this.
The format of `java.protocol.handler.pkgs` is typically described in java.net.URL(String,String,int,String)
See also
java.lang.System.setProperty(String,String)
commons.net.ssh seems to fall apart when addProvider() is used -- registering a dupe and crapping-the-bed -- but net.schmizz.sshj needs this
Definition at line 137 of file SSHCLI.java.
Referenced by SSHCLI.SSHCLI().
The documentation for this class was generated from the following file:
java/SSHCLI.java