CIMXMLWQLURLConnection Class Reference
Data Structures
class ResultCSVPipe
PipedOutputStream to push out resultsets as CSV Nicknames.
Public Member Functions
CIMXMLWQLURLConnection (String connectionInfo, String username, String password)
CIMXMLWQLURLConnection (java.net.URL url)
void setRequestHeader (String name, String value)
Stubbed, because there's no change we want to accept yet.
void setContentType (String ignored)
Stubbed, because there's no change we want to accept yet.
java.io.OutputStream getOutputStream ()
Stubbed, because there's nothing to send us.
java.io.InputStream getInputStream ()
connect the result of a `SELECT hp.wwn, h.name FROM host_port hp JOIN host h ON (h.id = hp.hostid)` to something that looks readable like an InputStream
void connect ()
Static Public Member Functions
static Subject getSubjectAuth (String authInfo)
static WBEMClient getWBEMClient (java.net.URL u) throws WBEMException
Protected Member Functions
CIMXMLWQLURLConnection openConnection (java.net.URL url)
openConnection(java.net.URL) overrides java.net.URLStreamHandler.openConnection(URL) by wrapping a pgsql client.
Protected Attributes
WBEMClient client = null
CIMObjectPath cop = null
String path = `/cimv2`
Detailed Description
Definition at line 47 of file CIMXMLWQLURLConnection.java.
Constructor & Destructor Documentation
CIMXMLWQLURLConnection (String connectionInfo, String username, String password) [inline]
Definition at line 105 of file CIMXMLWQLURLConnection.java.
CIMXMLWQLURLConnection (java.net.URL url) [inline]
Definition at line 115 of file CIMXMLWQLURLConnection.java.
Member Function Documentation
void connect () [inline]
Definition at line 268 of file CIMXMLWQLURLConnection.java.
References CIMXMLWQLURLConnection.getWBEMClient().
Referenced by CIMXMLWQLURLConnection.getInputStream().
java.io.InputStream getInputStream () [inline]
connect the result of a `SELECT hp.wwn, h.name FROM host_port hp JOIN host h ON (h.id = hp.hostid)` to something that looks readable like an InputStream
Definition at line 176 of file CIMXMLWQLURLConnection.java.
References CIMXMLWQLURLConnection.connect().
java.io.OutputStream getOutputStream () [inline]
Stubbed, because there's nothing to send us.
Oh how did I get caught in the `Royal 'We'` ?
Definition at line 167 of file CIMXMLWQLURLConnection.java.
static Subject getSubjectAuth (String authInfo) [inline], [static]
Definition at line 202 of file CIMXMLWQLURLConnection.java.
Referenced by CIMXMLWQLURLConnection.getWBEMClient().
static WBEMClient getWBEMClient (java.net.URL u) throws WBEMException [inline], [static]
Definition at line 227 of file CIMXMLWQLURLConnection.java.
References CIMXMLWQLURLConnection.getSubjectAuth().
Referenced by CIMXMLWQLURLConnection.connect().
CIMXMLWQLURLConnection openConnection (java.net.URL url) [inline], [protected]
openConnection(java.net.URL) overrides java.net.URLStreamHandler.openConnection(URL) by wrapping a pgsql client.
Returns
populated connection as org.smallfoot.cimcql.CIMXMLWQLURLConnection(Connection)
Parameters
url URL to connect to
Definition at line 249 of file CIMXMLWQLURLConnection.java.
void setContentType (String ignored) [inline]
Stubbed, because there's no change we want to accept yet.
Parameters
ignored ignored
Definition at line 162 of file CIMXMLWQLURLConnection.java.
void setRequestHeader (String name, String value) [inline]
Stubbed, because there's no change we want to accept yet.
Parameters
name ignored
value ignored
Definition at line 155 of file CIMXMLWQLURLConnection.java.
Field Documentation
WBEMClient client = null [protected]
Definition at line 101 of file CIMXMLWQLURLConnection.java.
CIMObjectPath cop = null [protected]
Definition at line 102 of file CIMXMLWQLURLConnection.java.
String path = `/cimv2` [protected]
Definition at line 103 of file CIMXMLWQLURLConnection.java.
The documentation for this class was generated from the following file:
java/CIMXMLWQLURLConnection.java