OSMURLConnection Class Reference
Data Structures
class ResultCSVPipe
PipedOutputStream to push out resultsets as CSV Nicknames.
Public Member Functions
OSMURLConnection (String connectionInfo, String username, String password)
OSMURLConnection (java.net.URL url)
void setRequestHeader (String name, String value)
Stubbed, because there's no change we want to accept yet.
void setContentType (String ignored)
Stubbed, because there's no change we want to accept yet.
java.io.OutputStream getOutputStream ()
Stubbed, because there's nothing to send us.
java.io.InputStream getInputStream ()
connect the result of a `SELECT hp.wwn, h.name FROM host_port hp JOIN host h ON (h.id = hp.hostid)` to something that looks readable like an InputStream
void connect ()
Protected Member Functions
OSMURLConnection openConnection (java.net.URL url)
openConnection(java.net.URL) overrides java.net.URLStreamHandler.openConnection(URL) by wrapping a pgsql client.
Protected Attributes
java.sql.Connection connection
Detailed Description
Definition at line 32 of file OSMURLConnection.java.
Constructor & Destructor Documentation
OSMURLConnection (String connectionInfo, String username, String password) [inline]
Definition at line 94 of file OSMURLConnection.java.
OSMURLConnection (java.net.URL url) [inline]
Definition at line 103 of file OSMURLConnection.java.
Member Function Documentation
void connect () [inline]
Definition at line 216 of file OSMURLConnection.java.
References OSMURLConnection.connection.
Referenced by MSDWHURLConnection.getInputStream(), and OSMURLConnection.getInputStream().
java.io.InputStream getInputStream () [inline]
connect the result of a `SELECT hp.wwn, h.name FROM host_port hp JOIN host h ON (h.id = hp.hostid)` to something that looks readable like an InputStream
Definition at line 167 of file OSMURLConnection.java.
References OSMURLConnection.connect(), and OSMURLConnection.connection.
java.io.OutputStream getOutputStream () [inline]
Stubbed, because there's nothing to send us.
Oh how did I get caught in the `Royal 'We'` ?
Definition at line 158 of file OSMURLConnection.java.
OSMURLConnection openConnection (java.net.URL url) [inline], [protected]
openConnection(java.net.URL) overrides java.net.URLStreamHandler.openConnection(URL) by wrapping a pgsql client.
Returns
populated connection as org.smallfoot.osmsql.OSMURLConnection(Connection)
Parameters
url URL to connect to
Definition at line 197 of file OSMURLConnection.java.
void setContentType (String ignored) [inline]
Stubbed, because there's no change we want to accept yet.
Sorry, apparently `at this time` is more professional, if you listen to the wordy airport announcements.
Parameters
ignored ignored
Definition at line 153 of file OSMURLConnection.java.
void setRequestHeader (String name, String value) [inline]
Stubbed, because there's no change we want to accept yet.
Sorry, apparently `at this time` is more professional, if you listen to the wordy airport announcements.
Parameters
name ignored
value ignored
Definition at line 144 of file OSMURLConnection.java.
Field Documentation
java.sql.Connection connection [protected]
Definition at line 92 of file OSMURLConnection.java.
Referenced by OSMURLConnection.connect(), MSDWHURLConnection.getInputStream(), and OSMURLConnection.getInputStream().
The documentation for this class was generated from the following file:
java/OSMURLConnection.java