FCParser Class Reference
Static Public Member Functions
static java.io.InputStream openStream (String uri) throws java.io.FileNotFoundException, java.net.MalformedURLException, java.io.IOException
Produce an InputStream for the given uri in a way that corresponds to the url protocol.
static void registerProtocols ()
Collect in a single place the process to register protocol handlers.
static InputStream openSource (String url, boolean verbose, java.util.Properties prop)
Create a stream from a URL or file name with a convenience workaround for no-proto URLs.
static ZoneParser loadFile (InputStream is, String args0, boolean verbose, java.util.Properties prop)
Load a file from the resource given to a WWN/Nickname vector.
static void main (String args[])
Main function, as you can tell.
Detailed Description
Definition at line 29 of file FCParser.java.
Member Function Documentation
static ZoneParser loadFile (InputStream is, String args0, boolean verbose, java.util.Properties prop) [inline], [static]
Load a file from the resource given to a WWN/Nickname vector.
Returns
the number of things loaded (used to trigger obsessive retries to get around choking org.apache.commons.io.input.TeeInputStream)
Parameters
is the inputstream to parse from
args0 the args[0] value to substitute into the optional verbose output of oarsing results
verbose if true, parser results will be shown to stdout
prop Properties through which to pass post-URL options
Definition at line 165 of file FCParser.java.
References ZoneParser.aliasSize(), and ZoneParser.zoneSize().
Referenced by FCParser.main().
static void main (String args[]) [inline], [static]
Main function, as you can tell.
this function merely parses the command-line to dispatch actions to the meat of the meal above. I'm using an actual GetOpt because, yes, I'm a UNIX/C hack, re-using 3-decades-old knowledge, but this also preserves both extensibility and the ability to use longopts in scripts as a way to self-document what the tool's doing.
No real intelligence herein except the parse-and-redirect action.
Parameters
args as you'd expect, these are commandline arguments given when the jar is activated
Always always ALWAYS provide a quick reference and a version output
Commandline Options
Commandline Options -H|--help Show a simple help screen as a reminder of options which are understood by the application
Commandline Options
Commandline Options
java -jar fcparsers.jar --help
Commandline Options
Commandline Options -V|--version Show the current release version for reference
Commandline Options
Commandline Options
java -jar fcparsers.jar --version
.3-160
Commandline Options
Commandline Options -N|--nickname={file/uri} Import nicknames by parsing a text stream from various sources
Commandline Options
Commandline Options
 java -jar fcparsers.jar --nickname=switch44.zoneshow
Parse results for AliShowZoneParser:
Zones: 44
Aliases: 112 (names with one or more WWPNs)
Aliases: 136 (name/WWPN tuples)
 In this example, a zone file was parsed by the AliShowZoneParser resulting in 112 nicknames; due to duplicate nicknames, there are actually 136 unique WWPN/alias tuples, which means that (136-112) 24 of the WWPNs have the same alias as other WWPNs
Commandline Options
Commandline Options -!|--check Run an internal check that dependent drivers are available and registered
Definition at line 296 of file FCParser.java.
References FCParser.loadFile(), FCParser.openSource(), FCParser.registerProtocols(), and ZoneParser.summarize().
static InputStream openSource (String url, boolean verbose, java.util.Properties prop) [inline], [static]
Create a stream from a URL or file name with a convenience workaround for no-proto URLs.
NOTE: changes java.util.Properties
Returns
the resulting InputStream
Parameters
url the resource to open
verbose whether to report errors to stdout or run quietly
prop Properties through which to pass post-URL options
Definition at line 97 of file FCParser.java.
References FCParser.openStream().
Referenced by FCParser.main().
static java.io.InputStream openStream (String uri) throws java.io.FileNotFoundException, java.net.MalformedURLException, java.io.IOException [inline], [static]
Produce an InputStream for the given uri in a way that corresponds to the url protocol.
Returns
InputStream ready to offer back the data
Parameters
uri the file:// resource of a file, ie `file:///sample.csv`
Definition at line 37 of file FCParser.java.
Referenced by FCParser.openSource().
static void registerProtocols () [inline], [static]
Collect in a single place the process to register protocol handlers.
This function checks for current protocol handlers and adds the ones we bring to that list. If no `java.protocol.handler.pkgs` exists, we simply provide one. System Properties are overwritten in this process.
as the number of handlers increases, we can make corresponding changes herein without consuming projects having to know or care about this.
The format of `java.protocol.handler.pkgs` is typically described in java.net.URL(String,String,int,String)
See also
java.lang.System.setProperty(String,String)
Definition at line 66 of file FCParser.java.
Referenced by FCParser.main().
The documentation for this class was generated from the following file:
java/FCParser.java