Alias4Parser Class Reference
Public Member Functions
void setDebug (boolean debug)
void setReader (java.io.Reader is)
Alias4Parser (java.util.Properties in)
void run ()
Alias4Parser (java.io.InputStream in)
Create a parser with a new stream, defaulting to no debug, and verbose ZP debug.
Alias4Parser ()
Create a parser with a no stream or reader, fairly uncivilized, defaulting to no debug.
Alias4Parser (java.io.InputStream in, boolean debugMe)
Create a parser with a new stream.
Alias4Parser (Reader in, boolean debugMe)
Create a parser, setting the debug to true or false.
Static Public Member Functions
static void main (String args[])
Detailed Description
Definition at line 28 of file Alias4Parser.java.
Constructor & Destructor Documentation
Alias4Parser (java.util.Properties in) [inline]
Definition at line 45 of file Alias4Parser.java.
Alias4Parser (java.io.InputStream in) [inline]
Create a parser with a new stream, defaulting to no debug, and verbose ZP debug.
Parameters
in InputStream that is the source of bytes to consume
Definition at line 97 of file Alias4Parser.java.
Alias4Parser () [inline]
Create a parser with a no stream or reader, fairly uncivilized, defaulting to no debug.
Definition at line 106 of file Alias4Parser.java.
Referenced by Alias4Parser.main().
Alias4Parser (java.io.InputStream in, boolean debugMe) [inline]
Create a parser with a new stream.
Parameters
in InputStream that is the source of bytes to consume
debugMe true for debugging, false for no debug.
Definition at line 118 of file Alias4Parser.java.
Alias4Parser (Reader in, boolean debugMe) [inline]
Create a parser, setting the debug to true or false.
Parameters
in Reader that is the source of bytes to consume
debugMe true for debugging, false for no debug.
Definition at line 131 of file Alias4Parser.java.
References Alias4Parser.setDebug(), and Alias4Parser.setReader().
Member Function Documentation
static void main (String args[]) [inline], [static]
Definition at line 139 of file Alias4Parser.java.
References Alias4Parser.Alias4Parser(), and ZoneParserI.testSummary().
void run () [inline]
Definition at line 51 of file Alias4Parser.java.
void setDebug (boolean debug) [inline]
Definition at line 34 of file Alias4Parser.java.
Referenced by Alias4Parser.Alias4Parser().
void setReader (java.io.Reader is) [inline]
Definition at line 40 of file Alias4Parser.java.
Referenced by Alias4Parser.Alias4Parser().
The documentation for this class was generated from the following file:
java/Alias4Parser.java