//#############################################
//## file: ZoneParser.java
//## Generated by Byacc/j
//#############################################
package org.smallfoot.parser.zone;

/**
 * @file
 * Originally created by BYACC/J but extracted to allow parent ZoneParser class to be intelligent
 * BYACC/J Semantic Value for parser: ZoneParser
 * This class provides some of the functionality
 * of the yacc/C 'union' directive
 */
public class ZoneParserVal
{
/**
 * integer value of this 'union'
 */
public int ival;

/**
 * double value of this 'union'
 */
public double dval;

/**
 * string value of this 'union'
 */
public String sval;

/**
 * object value of this 'union'
 */
public Object obj;

//#############################################
//## C O N S T R U C T O R S
//#############################################
/**
 * Initialize me without a value
 */
public ZoneParserVal()
{
}
/**
 * Initialize me as an int
 */
public ZoneParserVal(int val)
{
  ival=val;
}

/**
 * Initialize me as a double
 */
public ZoneParserVal(double val)
{
  dval=val;
}

/**
 * Initialize me as a string
 */
public ZoneParserVal(String val)
{
  sval=val;
}

/**
 * Initialize me as an Object
 */
public ZoneParserVal(Object val)
{
  obj=val;
}
}//end class

//#############################################
//## E N D    O F    F I L E
//#############################################
